export const EthnicityTypes = [
  'American Indian or Alaska Native',
  'Asian',
  'Black or African American',
  'Hispanic or Latino',
  'Native Hawaiian or Other Pacific Islander',
  'White',
  'Undisclosed'
];

export const Genders = [
  'Male',
  'Female'
];

export const Countries = [
  'Canada',
  'Turkmenistan',
  'Saint Helena',
  'Saint Pierre and Miquelon',
  'Ethiopia',
  'Swaziland',
  'Palestine',
  'Cameroon',
  'Burkina Faso',
  'Northern Mariana Islands',
  'Bosnia and Herzegovina',
  'Dominica',
  'Liberia',
  'Maldives',
  'Tanzania',
  'CuraÃƒÂ§ao',
  'Isle of Man',
  'Monaco',
  'Wallis and Futuna',
  'Jersey',
  'Svalbard and Jan Mayen',
  'Tajikistan',
  'Turkey',
  'Afghanistan',
  'Andorra',
  'France',
  'Slovakia',
  'Vanuatu',
  'Nauru',
  'Norway',
  'Malawi',
  'Montenegro',
  'Republic of the Congo',
  'Dominican Republic',
  'Ghana',
  'Cayman Islands',
  'Libya',
  'Finland',
  'Central African Republic',
  'Liechtenstein',
  'East Timor',
  'United States',
  'Portugal',
  'Cyprus',
  'Christmas Island',
  'Malaysia',
  'Saint Martin',
  'U.S. Virgin Islands',
  'Kuwait',
  'Panama',
  'Costa Rica',
  'Luxembourg',
  'American Samoa',
  'Bahamas',
  'Gibraltar',
  'Ireland',
  'Palau',
  'Nigeria',
  'Ecuador',
  'Australia',
  'El Salvador',
  'Tuvalu',
  'Pitcairn Islands',
  'Thailand',
  'Belize',
  'Hong Kong',
  'Sierra Leone',
  'Georgia',
  'Denmark',
  'Philippines',
  'Morocco',
  'Guernsey',
  'Myanmar [Burma]',
  'Bonaire',
  'Estonia',
  'Kosovo',
  'Lebanon',
  'Uzbekistan',
  'Republic of Korea',
  'Colombia',
  'Taiwan',
  'Fiji',
  'Barbados',
  'Madagascar',
  'Italy',
  'Sudan',
  'Nepal',
  'Netherlands',
  'Suriname',
  'Anguilla',
  'Israel',
  'Senegal',
  'Papua New Guinea',
  'SÃƒÂ£o TomÃƒÂ© and PrÃƒÂ­ncipe',
  'Zimbabwe',
  'British Indian Ocean Territory',
  'Martinique',
  'Mauritania',
  'Trinidad and Tobago',
  'RÃƒÂ©union',
  'Latvia',
  'Japan',
  'Hashemite Kingdom of Jordan',
  'Guadeloupe',
  'Sint Maarten',
  'Mexico',
  'Serbia',
  'United Kingdom',
  'Congo',
  'Greece',
  'Paraguay',
  'Gabon',
  'Botswana',
  'Cambodia',
  'Aruba',
  'Saint-BarthÃƒÂ©lemy',
  'Argentina',
  'Bolivia',
  'Bahrain',
  'Saudi Arabia',
  'Cape Verde',
  'Slovenia',
  'Guatemala',
  'Guinea',
  'Spain',
  'Jamaica',
  'Oman',
  'Greenland',
  'French Guiana',
  'Niue',
  'New Zealand',
  'Yemen',
  'Pakistan',
  'Albania',
  'Samoa',
  'Norfolk Island',
  'United Arab Emirates',
  'Guam',
  'India',
  'Azerbaijan',
  'Lesotho',
  'Saint Vincent and the Grenadines',
  'Kenya',
  'Bangladesh',
  'Eritrea',
  'Solomon Islands',
  'Saint Lucia',
  'San Marino',
  'Mongolia',
  'Rwanda',
  'Somalia',
  'Peru',
  'Laos',
  'Cook Islands',
  'Benin',
  'Federated States of Micronesia',
  'Singapore',
  'Saint Kitts and Nevis',
  'Togo',
  'China',
  'Armenia',
  'Ukraine',
  'Tonga',
  'Indonesia',
  'Cuba',
  'Mauritius',
  'Sweden',
  'Vietnam',
  'British Virgin Islands',
  'Mali',
  'Vatican City',
  'Russia',
  'Bulgaria',
  'Romania',
  'Angola',
  'French Southern Territories',
  'Chad',
  'South Africa',
  'Tokelau',
  'Macao',
  'South Georgia and the South Sandwich Islands',
  'Qatar',
  'Austria',
  'Mozambique',
  'Uganda',
  'Hungary',
  'Niger',
  'Brazil',
  'Falkland Islands',
  'Faroe Islands',
  'Republic of Moldova',
  'Ivory Coast',
  'Syria',
  'Czech Republic',
  'Brunei',
  'Belarus',
  'Iran',
  'Algeria',
  'Republic of Lithuania',
  'Marshall Islands',
  'Chile',
  'Puerto Rico',
  'Belgium',
  'Kiribati',
  'Haiti',
  'Iraq',
  'Gambia',
  'Croatia',
  'French Polynesia',
  'Guinea-Bissau',
  'Switzerland',
  'Grenada',
  'Seychelles',
  'Uruguay',
  'Equatorial Guinea',
  'U.S. Minor Outlying Islands',
  'Tunisia',
  'Djibouti',
  'Bermuda',
  'Antigua and Barbuda',
  'Burundi',
  'Turks and Caicos Islands',
  'Bhutan',
  'Malta',
  'Venezuela',
  'Iceland',
  'Zambia',
  'Germany',
  'Kazakhstan',
  'Poland',
  'Kyrgyzstan',
  'Mayotte',
  'Montserrat',
  'New Caledonia',
  'Macedonia',
  'North Korea',
  'South Sudan',
  'Guyana',
  'Honduras',
  'Egypt',
  'Nicaragua',
  'Cocos [Keeling] Islands',
  'Antarctica',
  'Sri Lanka',
  'Namibia',
  'Ãƒâ€¦land',
  'Comoros'
];
